import {
  STABILITY_STANDARD_SEED_MAX,
  UINT32_MAX,
  type CapabilityCategory,
  type CapabilityDescriptor,
  type RequestParameter,
} from '@harness/contracts';

export const CAPABILITY_REGISTRY_VERSION = '2026-08-06.1' as const;

function imageService<const Id extends string>(
  id: Id,
  name: string,
  category: Exclude<CapabilityCategory, 'generation'>,
  profileId: string,
  parameters: readonly RequestParameter[],
  seedMaximum?: number,
) {
  return {
    canonicalId: `service/${id}` as const,
    name,
    category,
    invocation: { kind: 'geo-inference-profile' as const, profileId },
    modes: ['image-service'] as const,
    parameters,
    outputFormats: ['jpeg', 'png', 'webp'] as const,
    ...(seedMaximum === undefined ? {} : { seedMaximum }),
  };
}

export const capabilityCatalog = [
  {
    canonicalId: 'generation/core',
    name: 'Stable Image Core',
    category: 'generation',
    invocation: {
      kind: 'foundation-model',
      modelId: 'stability.stable-image-core-v1:1',
    },
    modes: ['text-to-image'],
    parameters: ['prompt', 'negative_prompt', 'aspect_ratio', 'seed', 'output_format'],
    outputFormats: ['jpeg', 'png'],
    seedMaximum: UINT32_MAX,
  },
  {
    canonicalId: 'generation/ultra',
    name: 'Stable Image Ultra',
    category: 'generation',
    invocation: {
      kind: 'foundation-model',
      modelId: 'stability.stable-image-ultra-v1:1',
    },
    modes: ['text-to-image', 'image-to-image'],
    parameters: [
      'prompt',
      'negative_prompt',
      'aspect_ratio',
      'mode',
      'image',
      'strength',
      'seed',
      'output_format',
    ],
    outputFormats: ['jpeg', 'png'],
    seedMaximum: UINT32_MAX,
  },
  {
    canonicalId: 'generation/sd3.5-large',
    name: 'Stable Diffusion 3.5 Large',
    category: 'generation',
    invocation: {
      kind: 'foundation-model',
      modelId: 'stability.sd3-5-large-v1:0',
    },
    modes: ['text-to-image', 'image-to-image'],
    parameters: [
      'prompt',
      'negative_prompt',
      'aspect_ratio',
      'mode',
      'image',
      'strength',
      'seed',
      'output_format',
    ],
    outputFormats: ['jpeg', 'png', 'webp'],
    seedMaximum: STABILITY_STANDARD_SEED_MAX,
  },
  imageService(
    'control-sketch',
    'Control Sketch',
    'control',
    'us.stability.stable-image-control-sketch-v1:0',
    [
      'prompt',
      'image',
      'control_strength',
      'negative_prompt',
      'seed',
      'output_format',
      'style_preset',
    ],
    STABILITY_STANDARD_SEED_MAX,
  ),
  imageService(
    'control-structure',
    'Control Structure',
    'control',
    'us.stability.stable-image-control-structure-v1:0',
    [
      'prompt',
      'image',
      'control_strength',
      'negative_prompt',
      'seed',
      'output_format',
      'style_preset',
    ],
    STABILITY_STANDARD_SEED_MAX,
  ),
  imageService(
    'style-guide',
    'Style Guide',
    'control',
    'us.stability.stable-image-style-guide-v1:0',
    [
      'prompt',
      'image',
      'aspect_ratio',
      'fidelity',
      'negative_prompt',
      'seed',
      'output_format',
      'style_preset',
    ],
    STABILITY_STANDARD_SEED_MAX,
  ),
  imageService(
    'style-transfer',
    'Style Transfer',
    'control',
    'us.stability.stable-style-transfer-v1:0',
    [
      'init_image',
      'style_image',
      'prompt',
      'negative_prompt',
      'seed',
      'output_format',
      'composition_fidelity',
      'style_strength',
      'change_strength',
    ],
    STABILITY_STANDARD_SEED_MAX,
  ),
  imageService(
    'creative-upscale',
    'Creative Upscale',
    'upscale',
    'us.stability.stable-creative-upscale-v1:0',
    ['prompt', 'image', 'creativity', 'negative_prompt', 'seed', 'output_format', 'style_preset'],
    STABILITY_STANDARD_SEED_MAX,
  ),
  imageService(
    'conservative-upscale',
    'Conservative Upscale',
    'upscale',
    'us.stability.stable-conservative-upscale-v1:0',
    ['prompt', 'image', 'creativity', 'negative_prompt', 'seed', 'output_format'],
    STABILITY_STANDARD_SEED_MAX,
  ),
  imageService('fast-upscale', 'Fast Upscale', 'upscale', 'us.stability.stable-fast-upscale-v1:0', [
    'image',
    'output_format',
  ]),
  imageService(
    'inpaint',
    'Inpaint',
    'edit',
    'us.stability.stable-image-inpaint-v1:0',
    [
      'prompt',
      'image',
      'mask',
      'grow_mask',
      'negative_prompt',
      'seed',
      'output_format',
      'style_preset',
    ],
    STABILITY_STANDARD_SEED_MAX,
  ),
  imageService(
    'outpaint',
    'Outpaint',
    'edit',
    'us.stability.stable-outpaint-v1:0',
    [
      'image',
      'prompt',
      'style_preset',
      'seed',
      'output_format',
      'creativity',
      'left',
      'right',
      'up',
      'down',
    ],
    STABILITY_STANDARD_SEED_MAX,
  ),
  imageService(
    'search-recolor',
    'Search & Recolor',
    'edit',
    'us.stability.stable-image-search-recolor-v1:0',
    [
      'prompt',
      'image',
      'select_prompt',
      'grow_mask',
      'negative_prompt',
      'seed',
      'output_format',
      'style_preset',
    ],
    STABILITY_STANDARD_SEED_MAX,
  ),
  imageService(
    'search-replace',
    'Search & Replace',
    'edit',
    'us.stability.stable-image-search-replace-v1:0',
    [
      'prompt',
      'image',
      'search_prompt',
      'grow_mask',
      'negative_prompt',
      'seed',
      'output_format',
      'style_preset',
    ],
    STABILITY_STANDARD_SEED_MAX,
  ),
  imageService(
    'erase',
    'Erase Object',
    'edit',
    'us.stability.stable-image-erase-object-v1:0',
    ['image', 'mask', 'grow_mask', 'seed', 'output_format'],
    STABILITY_STANDARD_SEED_MAX,
  ),
  imageService(
    'remove-background',
    'Remove Background',
    'edit',
    'us.stability.stable-image-remove-background-v1:0',
    ['image', 'output_format'],
  ),
] as const satisfies readonly CapabilityDescriptor[];

export type CanonicalCapabilityId = (typeof capabilityCatalog)[number]['canonicalId'];

const canonicalCapabilityIds = new Set<string>(
  capabilityCatalog.map((capability) => capability.canonicalId),
);

export function isCanonicalCapabilityId(value: string): value is CanonicalCapabilityId {
  return canonicalCapabilityIds.has(value);
}
